In [1]:
import numpy as np
rng = np.random.default_rng(seed=42) # random number generator

- np array is collection of objects of homegeneous type
- strided access the array is a `view` operation not a copy
- ndarray consists of 
    - pointer to data - block in RAM or a memory mapped file
    - `dtype`
    - tuple for array shape
    - tuple of stride in bytes to indicate steps in order to advance one element along a dimension



In [2]:
a = np.ones((3,4,4), dtype=np.float64)
a.strides

(128, 32, 8)

# Data type hierarchy
- np.integer is superclass of all integer types
- np.floating is superclass of all floating types
- np.issubdtype is used to check type of array

In [4]:
np.issubdtype(a.dtype, np.floating)

True

In [5]:
np.issubdtype(a.dtype, np.integer)

False

In [8]:
np.floating.mro() # parent classes of np.floating

[numpy.floating, numpy.inexact, numpy.number, numpy.generic, object]

In [9]:
np.integer.mro()

[numpy.integer, numpy.number, numpy.generic, object]

In [10]:
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

# Advance ops

## Reshaping arrays

In [13]:
a = np.arange(8)
b = a.reshape((4,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [14]:
b.reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [15]:
c = np.arange(15)
c.reshape((5, -1)) # passing -1 auto-infers value from data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [24]:
other_arr = rng.standard_normal((3, 5))
other_arr

array([[-0.85929246,  0.36875078, -0.9588826 ,  0.8784503 , -0.04992591],
       [-0.18486236, -0.68092954,  1.22254134, -0.15452948, -0.42832782],
       [-0.35213355,  0.53230919,  0.36544406,  0.41273261,  0.430821  ]])

In [25]:
c.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

`ravel` and `flatten` are opposite of reshape
- `flatten` always produces a copy
- `ravel` doesn't produce a copy of underlying data if the elements were contiguous in memory

In [40]:
d = other_arr.ravel()

In [41]:
id(other_arr)

140168017857296

In [42]:
id(d)

140168017822512

In [43]:
c = other_arr.flatten()
id(c)

In [45]:
d[0] = 0
other_arr

array([[ 0.        ,  0.36875078, -0.9588826 ,  0.8784503 , -0.04992591],
       [-0.18486236, -0.68092954,  1.22254134, -0.15452948, -0.42832782],
       [-0.35213355,  0.53230919,  0.36544406,  0.41273261,  0.430821  ]])

In [46]:
c[1] = 2
other_arr

array([[ 0.        ,  0.36875078, -0.9588826 ,  0.8784503 , -0.04992591],
       [-0.18486236, -0.68092954,  1.22254134, -0.15452948, -0.42832782],
       [-0.35213355,  0.53230919,  0.36544406,  0.41273261,  0.430821  ]])

In [47]:
c

array([ 0.        ,  2.        , -0.9588826 ,  0.8784503 , -0.04992591,
       -0.18486236, -0.68092954,  1.22254134, -0.15452948, -0.42832782,
       -0.35213355,  0.53230919,  0.36544406,  0.41273261,  0.430821  ])

In [50]:
# raveling in column major order
other_arr.ravel('F') # transposes the array and then ravel

array([ 0.        , -0.18486236, -0.35213355,  0.36875078, -0.68092954,
        0.53230919, -0.9588826 ,  1.22254134,  0.36544406,  0.8784503 ,
       -0.15452948,  0.41273261, -0.04992591, -0.42832782,  0.430821  ])

### concatenate

In [53]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([[7, 8, 9], [10, 11, 12]])

np.concatenate([arr1, arr2], axis=0)



array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [54]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

`vstack` and `hstack`

In [55]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

`split` slices an array along an axis

In [57]:
arr = rng.standard_normal((5,4,3))
arr

array([[[ 2.1416476 , -0.40641502, -0.51224273],
        [-0.81377273,  0.61597942,  1.12897229],
        [-0.11394746, -0.84015648, -0.82448122],
        [ 0.65059279,  0.74325417,  0.54315427]],

       [[-0.66550971,  0.23216132,  0.11668581],
        [ 0.2186886 ,  0.87142878,  0.22359555],
        [ 0.67891356,  0.06757907,  0.2891194 ],
        [ 0.63128823, -1.45715582, -0.31967122]],

       [[-0.47037265, -0.63887785, -0.27514225],
        [ 1.49494131, -0.86583112,  0.96827835],
        [-1.68286977, -0.33488503,  0.16275307],
        [ 0.58622233,  0.71122658,  0.79334724]],

       [[-0.34872507, -0.46235179,  0.85797588],
        [-0.19130432, -1.27568632, -1.13328721],
        [-0.91945229,  0.49716074,  0.14242574],
        [ 0.69048535, -0.42725265,  0.15853969]],

       [[ 0.62559039, -0.30934654,  0.45677524],
        [-0.66192594, -0.36305385, -0.38173789],
        [-1.19583965,  0.48697248, -0.46940234],
        [ 0.01249412,  0.48074666,  0.44653118]]])

In [59]:
first, second, third = np.split(arr, [1, 4])

In [62]:
print(first)
print("\n\n")
print(second)
print("\n\n")
print(third)

[[[ 2.1416476  -0.40641502 -0.51224273]
  [-0.81377273  0.61597942  1.12897229]
  [-0.11394746 -0.84015648 -0.82448122]
  [ 0.65059279  0.74325417  0.54315427]]]



[[[-0.66550971  0.23216132  0.11668581]
  [ 0.2186886   0.87142878  0.22359555]
  [ 0.67891356  0.06757907  0.2891194 ]
  [ 0.63128823 -1.45715582 -0.31967122]]

 [[-0.47037265 -0.63887785 -0.27514225]
  [ 1.49494131 -0.86583112  0.96827835]
  [-1.68286977 -0.33488503  0.16275307]
  [ 0.58622233  0.71122658  0.79334724]]

 [[-0.34872507 -0.46235179  0.85797588]
  [-0.19130432 -1.27568632 -1.13328721]
  [-0.91945229  0.49716074  0.14242574]
  [ 0.69048535 -0.42725265  0.15853969]]]



[[[ 0.62559039 -0.30934654  0.45677524]
  [-0.66192594 -0.36305385 -0.38173789]
  [-1.19583965  0.48697248 -0.46940234]
  [ 0.01249412  0.48074666  0.44653118]]]


In [66]:
np.hsplit(arr, [1,2])

[array([[[ 2.1416476 , -0.40641502, -0.51224273]],
 
        [[-0.66550971,  0.23216132,  0.11668581]],
 
        [[-0.47037265, -0.63887785, -0.27514225]],
 
        [[-0.34872507, -0.46235179,  0.85797588]],
 
        [[ 0.62559039, -0.30934654,  0.45677524]]]),
 array([[[-0.81377273,  0.61597942,  1.12897229]],
 
        [[ 0.2186886 ,  0.87142878,  0.22359555]],
 
        [[ 1.49494131, -0.86583112,  0.96827835]],
 
        [[-0.19130432, -1.27568632, -1.13328721]],
 
        [[-0.66192594, -0.36305385, -0.38173789]]]),
 array([[[-0.11394746, -0.84015648, -0.82448122],
         [ 0.65059279,  0.74325417,  0.54315427]],
 
        [[ 0.67891356,  0.06757907,  0.2891194 ],
         [ 0.63128823, -1.45715582, -0.31967122]],
 
        [[-1.68286977, -0.33488503,  0.16275307],
         [ 0.58622233,  0.71122658,  0.79334724]],
 
        [[-0.91945229,  0.49716074,  0.14242574],
         [ 0.69048535, -0.42725265,  0.15853969]],
 
        [[-1.19583965,  0.48697248, -0.46940234],
        

## stacking helpers
special objects in namespaces, `r_` and `c_` which make stacking arrays more concise

In [68]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = rng.standard_normal((3, 2))
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-1.32269961, -0.99724683],
       [ 0.39977423, -0.90547906],
       [-0.37816255,  1.2992283 ]])

In [69]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -1.32269961, -0.99724683],
       [ 2.        ,  3.        ,  0.39977423, -0.90547906],
       [ 4.        ,  5.        , -0.37816255,  1.2992283 ]])

In [71]:
np.c_[1:6, -10:-5] # turn slices to arrays

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

## Repeating elements

 # fancy Indexing

In [2]:
import numpy as np

In [14]:
rng = np.random.default_rng(seed=42)
arr = rng.standard_normal((2, 4))
arr

array([[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259]])

In [15]:
inds = [2, 0, 2, 1]
b = arr[:, inds]

In [16]:
c = arr.take(inds, 1)

In [17]:
b[0, 1] = 0

In [18]:
arr

array([[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259]])

In [19]:
b

array([[ 0.7504512 ,  0.        ,  0.7504512 , -1.03998411],
       [ 0.1278404 , -1.95103519,  0.1278404 , -1.30217951]])

In [20]:
c[0,1] = 0

In [21]:
arr

array([[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259]])

In [22]:
d = arr[:2]

In [23]:
d

array([[ 0.30471708, -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259]])

In [24]:
d[0,0] = 0
arr

array([[ 0.        , -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259]])

In [25]:
e = arr.take([0,1,2], axis=1)

In [26]:
e

array([[ 0.        , -1.03998411,  0.7504512 ],
       [-1.95103519, -1.30217951,  0.1278404 ]])

In [27]:
e[0,1] = 0
arr

array([[ 0.        , -1.03998411,  0.7504512 ,  0.94056472],
       [-1.95103519, -1.30217951,  0.1278404 , -0.31624259]])

# Broadcasting